logging:
  level:
    org:
      elasticsearch: debug
      springframework: debug
wechat:
  url: https://api.weixin.qq.com
  appId: wx87d22b0ea1d45c6d
  secret: 9409d2e83ad0a849cb6f3c6c13033f5d
  vToken:
server:
  port: 8898
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  application:
    name: service1
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9200
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/lbsj?useUnicode=yes&characterEncoding=UTF8&useSSL=false&autoReconnect=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    hikari:
      keepalive-time: 6000
      auto-commit: true
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 60000
      max-lifetime: 60000
      idle-timeout: 50000
      connection-test-query: select 1
#  redis:
#    host: 127.0.0.1
#    port: 6381
#    password: 123456
#    timeout: 10000
#    lettuce:
#      pool:
#        # 连接池中的最大空闲连接
#        max-idle: 200
#        # 连接池中的最小空闲连接
#        min-idle: 1
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1
#        # 连接池最大连接数（使用负值表示没有限制）
#        max-active: 200
#    sentinel:
#      master: mymaster
#      nodes: 127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381
#  redis-stream:
#    key: test001
#    group: group001

elasticsearch:
  address: 110.41.185.137:9200
  username: elastic
  password: lbsj_dev123
  scheme: https
  connectTimeout: 5000
  socketTimeout: 5000
  connectionRequestTimeout: 5000
  maxConnectNum: 100
  maxConnectPerRoute: 100